create extension if not exists "hypopg" with schema "extensions";
create extension if not exists "index_advisor" with schema "extensions";
drop extension if exists "pg_net";
create schema if not exists "security";
create type "public"."app_permission" as enum ('links.create', 'links.read', 'links.update', 'links.delete', 'links.transfer', 'stats.view', 'stats.export', 'stats.view_sensitive', 'domains.add', 'domains.delete', 'domains.verify', 'domains.read', 'team.read', 'team.invite', 'team.remove', 'team.manage_roles', 'admin.read', 'admin.manage_users', 'admin.manage_permissions', 'admin.manage_plans', 'admin.manage_billing', 'admin.access_audit_log', 'security.blacklist_domains', 'security.whitelist_domains', 'security.view_protected', 'security.change_ratelimits', 'system.view_health', 'system.restart_workers', 'system.manage_keys');
create type "public"."app_plan" as enum ('basic', 'pro', 'free');
create type "public"."app_role" as enum ('user', 'editor', 'manager', 'admin');
create table "public"."audit_logs" (
    "id" uuid not null default gen_random_uuid(),
    "entity_type" text,
    "entity_id" uuid,
    "action" text,
    "old_data" jsonb,
    "new_data" jsonb,
    "user_id" uuid,
    "created_at" timestamp with time zone default now()
      );
alter table "public"."audit_logs" enable row level security;
create table "public"."discounts" (
    "id" uuid not null default gen_random_uuid(),
    "code" text not null,
    "description" text,
    "discount_type" text not null,
    "amount" numeric(10,2) not null,
    "currency" text default 'USD'::text,
    "applies_to" text default 'order'::text,
    "service_id" uuid,
    "usage_limit" integer,
    "used_count" integer default 0,
    "valid_from" timestamp with time zone default now(),
    "valid_until" timestamp with time zone,
    "active" boolean default true,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );
alter table "public"."discounts" enable row level security;
create table "public"."domains_to_check" (
    "id" bigint generated by default as identity not null,
    "domain" text,
    "validated" boolean not null default false
      );
alter table "public"."domains_to_check" enable row level security;
create table "public"."history_clicks" (
    "id" bigint generated by default as identity not null,
    "slug" text not null,
    "ip" text,
    "country_code" text,
    "domain" text,
    "utm_source" text,
    "utm_medium" text,
    "utm_campaign" text,
    "created_at" timestamp with time zone not null default now(),
    "utm_content" text,
    "utm_term" text,
    "utm_id" text,
    "region" text,
    "city" text,
    "latitude" text,
    "longitude" text,
    "user_agent" text,
    "is_bot" boolean not null default false,
    "browser" text,
    "browser_version" text,
    "device_type" text,
    "device_vendor" text,
    "device_model" text,
    "os" text,
    "os_version" text,
    "referer" text
      );
alter table "public"."history_clicks" enable row level security;
create table "public"."orders" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "service_id" uuid,
    "discount_id" uuid,
    "amount" numeric(10,2) not null,
    "discount_amount" numeric(10,2) default 0,
    "currency" text default 'USD'::text,
    "status" text default 'pending'::text,
    "payment_gateway" text default 'paypal'::text,
    "external_order_id" text,
    "description" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );
alter table "public"."orders" enable row level security;
create table "public"."payments" (
    "id" uuid not null default gen_random_uuid(),
    "order_id" uuid,
    "gateway" text default 'paypal'::text,
    "external_payment_id" text,
    "status" text default 'created'::text,
    "amount" numeric(10,2),
    "currency" text,
    "payer_email" text,
    "payer_id" text,
    "raw_response" jsonb,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );
alter table "public"."payments" enable row level security;
create table "public"."plan_permission" (
    "id" bigint generated by default as identity not null,
    "plan" public.app_plan not null,
    "permission" public.app_permission not null
      );
alter table "public"."plan_permission" enable row level security;
create table "public"."role_permissions" (
    "id" bigint generated by default as identity not null,
    "role" public.app_role not null,
    "permission" public.app_permission not null
      );
alter table "public"."role_permissions" enable row level security;
create table "public"."services" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "description" text,
    "price" numeric(10,2) not null,
    "currency" text default 'USD'::text,
    "type" text not null,
    "interval" text,
    "active" boolean default true,
    "created_at" timestamp with time zone default now(),
    "service_gateway" text default 'paypal'::text,
    "external_service_id" text default ''::text
      );
alter table "public"."services" enable row level security;
create table "public"."short_links" (
    "slug" text not null,
    "destination" text,
    "created_at" timestamp with time zone not null default now(),
    "utm_source" text,
    "utm_medium" text,
    "utm_campaign" text,
    "clicks" bigint default '0'::bigint,
    "user_id" uuid,
    "ip_user" text,
    "country_code_user" text,
    "domain" text,
    "utm_content" text,
    "utm_term" text,
    "utm_id" text,
    "status" boolean not null default true,
    "expires_in" integer,
    "expires_at" timestamp with time zone,
    "alias" text
      );
alter table "public"."short_links" enable row level security;
create table "public"."short_links_daily_stats" (
    "slug" text not null,
    "date" date not null,
    "total_clicks" integer not null default 0,
    "unique_ips" integer not null default 0,
    "country_counts" jsonb not null default '{}'::jsonb,
    "browser_counts" jsonb not null default '{}'::jsonb,
    "os_counts" jsonb not null default '{}'::jsonb,
    "device_type_counts" jsonb not null default '{}'::jsonb,
    "updated_at" timestamp with time zone default now()
      );
alter table "public"."short_links_daily_stats" enable row level security;
create table "public"."short_links_monthly_stats" (
    "slug" text not null,
    "year" integer not null,
    "month" integer not null,
    "total_clicks" integer not null default 0,
    "unique_ips" integer not null default 0,
    "country_counts" jsonb not null default '{}'::jsonb,
    "browser_counts" jsonb not null default '{}'::jsonb,
    "os_counts" jsonb not null default '{}'::jsonb,
    "device_type_counts" jsonb not null default '{}'::jsonb,
    "updated_at" timestamp with time zone default now()
      );
alter table "public"."short_links_monthly_stats" enable row level security;
create table "public"."short_links_stats" (
    "slug" text not null,
    "total_clicks" bigint not null default 0,
    "unique_ips" bigint not null default 0,
    "last_click_at" timestamp with time zone,
    "country_counts" jsonb not null default '{}'::jsonb,
    "browser_counts" jsonb not null default '{}'::jsonb,
    "os_counts" jsonb not null default '{}'::jsonb,
    "device_type_counts" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );
alter table "public"."short_links_stats" enable row level security;
create table "public"."subscriptions" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "service_id" uuid,
    "subscription_gateway" text default 'paypal'::text,
    "external_subscription_id" text,
    "status" text default 'active'::text,
    "start_date" timestamp with time zone default now(),
    "end_date" timestamp with time zone,
    "next_billing_date" timestamp with time zone,
    "cancel_reason" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );
alter table "public"."subscriptions" enable row level security;
create table "public"."user_roles" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "role" public.app_role not null
      );
alter table "public"."user_roles" enable row level security;
create table "public"."users_profiles" (
    "id" uuid not null,
    "full_name" text,
    "phone" text,
    "country" text,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "plan" public.app_plan not null default 'free'::public.app_plan,
    "timezone" text
      );
alter table "public"."users_profiles" enable row level security;
create table "public"."webhook_events" (
    "id" uuid not null default gen_random_uuid(),
    "gateway" text default 'paypal'::text,
    "event_type" text,
    "external_event_id" text,
    "payload" jsonb,
    "processed" boolean default false,
    "created_at" timestamp with time zone default now(),
    "summary" text,
    "resource_type" text
      );
alter table "public"."webhook_events" enable row level security;
create table "security"."blocked_url" (
    "domain" text not null,
    "is_custom" boolean not null default false,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
      );
alter table "security"."blocked_url" enable row level security;
create table "security"."blocklist_url_phishing_active" (
    "id" bigint generated by default as identity not null,
    "domain" text not null
      );
alter table "security"."blocklist_url_phishing_active" enable row level security;
create table "security"."cached_blocked_url" (
    "domain" text not null,
    "is_custom" boolean not null default false,
    "is_permanent" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
      );
alter table "security"."cached_blocked_url" enable row level security;
create table "security"."whitelist_url" (
    "domain" text not null,
    "is_custom" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
      );
alter table "security"."whitelist_url" enable row level security;
CREATE UNIQUE INDEX audit_logs_pkey ON public.audit_logs USING btree (id);
CREATE INDEX audit_logs_user_id_idx ON public.audit_logs USING btree (user_id);
CREATE UNIQUE INDEX discounts_code_key ON public.discounts USING btree (code);
CREATE UNIQUE INDEX discounts_pkey ON public.discounts USING btree (id);
CREATE INDEX discounts_service_id_idx ON public.discounts USING btree (service_id);
CREATE UNIQUE INDEX domains_to_check_pkey ON public.domains_to_check USING btree (id);
CREATE UNIQUE INDEX history_clicks_pkey ON public.history_clicks USING btree (id);
CREATE INDEX history_clicks_slug_idx ON public.history_clicks USING btree (slug);
CREATE INDEX orders_discount_id_idx ON public.orders USING btree (discount_id);
CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);
CREATE INDEX orders_service_id_idx ON public.orders USING btree (service_id);
CREATE INDEX orders_user_id_idx ON public.orders USING btree (user_id);
CREATE INDEX payments_order_id_idx ON public.payments USING btree (order_id);
CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (id);
CREATE UNIQUE INDEX plan_permission_pkey ON public.plan_permission USING btree (id);
CREATE UNIQUE INDEX role_permissions_pkey ON public.role_permissions USING btree (id);
CREATE UNIQUE INDEX role_permissions_role_permission_key ON public.role_permissions USING btree (role, permission);
CREATE UNIQUE INDEX services_pkey ON public.services USING btree (id);
CREATE UNIQUE INDEX short_links_daily_stats_pkey ON public.short_links_daily_stats USING btree (slug, date);
CREATE UNIQUE INDEX short_links_monthly_stats_pkey ON public.short_links_monthly_stats USING btree (slug, year, month);
CREATE UNIQUE INDEX short_links_pkey ON public.short_links USING btree (slug);
CREATE UNIQUE INDEX short_links_stats_pkey ON public.short_links_stats USING btree (slug);
CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);
CREATE INDEX subscriptions_service_id_idx ON public.subscriptions USING btree (service_id);
CREATE INDEX subscriptions_user_id_idx ON public.subscriptions USING btree (user_id);
CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (id);
CREATE UNIQUE INDEX user_roles_user_id_role_key ON public.user_roles USING btree (user_id, role);
CREATE UNIQUE INDEX users_profiles_pkey ON public.users_profiles USING btree (id);
CREATE UNIQUE INDEX webhook_events_external_event_id_key ON public.webhook_events USING btree (external_event_id);
CREATE UNIQUE INDEX webhook_events_pkey ON public.webhook_events USING btree (id);
CREATE UNIQUE INDEX blocked_url_2_pkey ON security.blocked_url USING btree (domain);
CREATE UNIQUE INDEX blocklist_url_phishing_active_pkey ON security.blocklist_url_phishing_active USING btree (id);
CREATE UNIQUE INDEX cache_blocked_url_pkey ON security.cached_blocked_url USING btree (domain);
CREATE UNIQUE INDEX whitelist_url_pkey ON security.whitelist_url USING btree (domain);
alter table "public"."audit_logs" add constraint "audit_logs_pkey" PRIMARY KEY using index "audit_logs_pkey";
alter table "public"."discounts" add constraint "discounts_pkey" PRIMARY KEY using index "discounts_pkey";
alter table "public"."domains_to_check" add constraint "domains_to_check_pkey" PRIMARY KEY using index "domains_to_check_pkey";
alter table "public"."history_clicks" add constraint "history_clicks_pkey" PRIMARY KEY using index "history_clicks_pkey";
alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";
alter table "public"."payments" add constraint "payments_pkey" PRIMARY KEY using index "payments_pkey";
alter table "public"."plan_permission" add constraint "plan_permission_pkey" PRIMARY KEY using index "plan_permission_pkey";
alter table "public"."role_permissions" add constraint "role_permissions_pkey" PRIMARY KEY using index "role_permissions_pkey";
alter table "public"."services" add constraint "services_pkey" PRIMARY KEY using index "services_pkey";
alter table "public"."short_links" add constraint "short_links_pkey" PRIMARY KEY using index "short_links_pkey";
alter table "public"."short_links_daily_stats" add constraint "short_links_daily_stats_pkey" PRIMARY KEY using index "short_links_daily_stats_pkey";
alter table "public"."short_links_monthly_stats" add constraint "short_links_monthly_stats_pkey" PRIMARY KEY using index "short_links_monthly_stats_pkey";
alter table "public"."short_links_stats" add constraint "short_links_stats_pkey" PRIMARY KEY using index "short_links_stats_pkey";
alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";
alter table "public"."user_roles" add constraint "user_roles_pkey" PRIMARY KEY using index "user_roles_pkey";
alter table "public"."users_profiles" add constraint "users_profiles_pkey" PRIMARY KEY using index "users_profiles_pkey";
alter table "public"."webhook_events" add constraint "webhook_events_pkey" PRIMARY KEY using index "webhook_events_pkey";
alter table "security"."blocked_url" add constraint "blocked_url_2_pkey" PRIMARY KEY using index "blocked_url_2_pkey";
alter table "security"."blocklist_url_phishing_active" add constraint "blocklist_url_phishing_active_pkey" PRIMARY KEY using index "blocklist_url_phishing_active_pkey";
alter table "security"."cached_blocked_url" add constraint "cache_blocked_url_pkey" PRIMARY KEY using index "cache_blocked_url_pkey";
alter table "security"."whitelist_url" add constraint "whitelist_url_pkey" PRIMARY KEY using index "whitelist_url_pkey";
alter table "public"."audit_logs" add constraint "audit_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;
alter table "public"."audit_logs" validate constraint "audit_logs_user_id_fkey";
alter table "public"."discounts" add constraint "discounts_applies_to_check" CHECK ((applies_to = ANY (ARRAY['service'::text, 'order'::text, 'subscription'::text]))) not valid;
alter table "public"."discounts" validate constraint "discounts_applies_to_check";
alter table "public"."discounts" add constraint "discounts_code_key" UNIQUE using index "discounts_code_key";
alter table "public"."discounts" add constraint "discounts_discount_type_check" CHECK ((discount_type = ANY (ARRAY['percent'::text, 'fixed'::text]))) not valid;
alter table "public"."discounts" validate constraint "discounts_discount_type_check";
alter table "public"."discounts" add constraint "discounts_service_id_fkey" FOREIGN KEY (service_id) REFERENCES public.services(id) not valid;
alter table "public"."discounts" validate constraint "discounts_service_id_fkey";
alter table "public"."history_clicks" add constraint "history_clicks_slug_fkey" FOREIGN KEY (slug) REFERENCES public.short_links(slug) not valid;
alter table "public"."history_clicks" validate constraint "history_clicks_slug_fkey";
alter table "public"."orders" add constraint "orders_discount_id_fkey" FOREIGN KEY (discount_id) REFERENCES public.discounts(id) not valid;
alter table "public"."orders" validate constraint "orders_discount_id_fkey";
alter table "public"."orders" add constraint "orders_service_id_fkey" FOREIGN KEY (service_id) REFERENCES public.services(id) not valid;
alter table "public"."orders" validate constraint "orders_service_id_fkey";
alter table "public"."orders" add constraint "orders_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text, 'cancelled'::text]))) not valid;
alter table "public"."orders" validate constraint "orders_status_check";
alter table "public"."orders" add constraint "orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."orders" validate constraint "orders_user_id_fkey";
alter table "public"."payments" add constraint "payments_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE not valid;
alter table "public"."payments" validate constraint "payments_order_id_fkey";
alter table "public"."payments" add constraint "payments_status_check" CHECK ((status = ANY (ARRAY['created'::text, 'authorized'::text, 'captured'::text, 'failed'::text, 'refunded'::text]))) not valid;
alter table "public"."payments" validate constraint "payments_status_check";
alter table "public"."role_permissions" add constraint "role_permissions_role_permission_key" UNIQUE using index "role_permissions_role_permission_key";
alter table "public"."services" add constraint "services_interval_check" CHECK (("interval" = ANY (ARRAY['day'::text, 'week'::text, 'month'::text, 'quarterly'::text, 'biannual'::text, 'year'::text]))) not valid;
alter table "public"."services" validate constraint "services_interval_check";
alter table "public"."services" add constraint "services_type_check" CHECK ((type = ANY (ARRAY['one_time'::text, 'subscription'::text]))) not valid;
alter table "public"."services" validate constraint "services_type_check";
alter table "public"."short_links_daily_stats" add constraint "short_links_daily_stats_slug_fkey" FOREIGN KEY (slug) REFERENCES public.short_links(slug) not valid;
alter table "public"."short_links_daily_stats" validate constraint "short_links_daily_stats_slug_fkey";
alter table "public"."short_links_monthly_stats" add constraint "short_links_monthly_stats_slug_fkey" FOREIGN KEY (slug) REFERENCES public.short_links(slug) not valid;
alter table "public"."short_links_monthly_stats" validate constraint "short_links_monthly_stats_slug_fkey";
alter table "public"."short_links_stats" add constraint "short_links_stats_slug_fkey" FOREIGN KEY (slug) REFERENCES public.short_links(slug) not valid;
alter table "public"."short_links_stats" validate constraint "short_links_stats_slug_fkey";
alter table "public"."subscriptions" add constraint "subscriptions_service_id_fkey" FOREIGN KEY (service_id) REFERENCES public.services(id) not valid;
alter table "public"."subscriptions" validate constraint "subscriptions_service_id_fkey";
alter table "public"."subscriptions" add constraint "subscriptions_status_check" CHECK ((status = ANY (ARRAY['APPROVAL_PENDING'::text, 'APPROVED'::text, 'ACTIVE'::text, 'SUSPENDED'::text, 'CANCELLED'::text, 'EXPIRED'::text]))) not valid;
alter table "public"."subscriptions" validate constraint "subscriptions_status_check";
alter table "public"."subscriptions" add constraint "subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."subscriptions" validate constraint "subscriptions_user_id_fkey";
alter table "public"."user_roles" add constraint "user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."user_roles" validate constraint "user_roles_user_id_fkey";
alter table "public"."user_roles" add constraint "user_roles_user_id_role_key" UNIQUE using index "user_roles_user_id_role_key";
alter table "public"."users_profiles" add constraint "users_profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."users_profiles" validate constraint "users_profiles_id_fkey";
alter table "public"."webhook_events" add constraint "webhook_events_external_event_id_key" UNIQUE using index "webhook_events_external_event_id_key";
set check_function_bodies = off;
CREATE OR REPLACE FUNCTION public.authorize(requested_permission public.app_permission)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  bind_permissions int;
  user_role public.app_role;
begin
  -- Fetch user role once and store it to reduce number of calls
  select (auth.jwt() ->> 'user_role')::public.app_role into user_role;

  select count(*)
  into bind_permissions
  from public.role_permissions
  where role_permissions.permission = requested_permission
    and role_permissions.role = user_role;

  return bind_permissions > 0;
end;
$function$;
CREATE OR REPLACE FUNCTION public.click_short_link(page_slug text, user_ip text, user_country_code text, user_region text, user_city text, user_latitude text, user_longitude text, user_ua text, user_is_bot boolean, user_browser text, user_browser_version text, user_device_type text, user_device_vendor text, user_device_model text, user_os text, user_os_version text, user_referer text)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$declare
  page_found text;
  page_domain text;
  page_utm_source text;
  page_utm_medium text;
  page_utm_campaign text;
  page_utm_content text;
  page_utm_term text;
  page_utm_id text;

BEGIN

SELECT 
  destination,
  domain,
  utm_source,
  utm_medium,
  utm_campaign,
  utm_content,
  utm_term,
  utm_id

  into page_found, 
  page_domain, 
  page_utm_source, 
  page_utm_medium,
  page_utm_campaign,
  page_utm_content,
  page_utm_term,
  page_utm_id
FROM public.short_links 
WHERE slug = page_slug;

if page_found is null then
  return;
end if;

UPDATE public.short_links
  SET clicks = clicks + 1
WHERE slug = page_slug;

INSERT INTO public.history_clicks (
  slug, ip, country_code, region, city, domain, 
  utm_source, utm_medium, utm_campaign, utm_content, utm_term, utm_id, 
  latitude, longitude, user_agent, is_bot, browser, browser_version, device_type, device_vendor, device_model, os, os_version, referer
) VALUES (
  page_slug, user_ip, user_country_code, user_region, user_city, page_domain, 
  page_utm_source, page_utm_medium, page_utm_campaign, page_utm_content, page_utm_term, page_utm_id, 
  user_latitude, user_longitude, user_ua, user_is_bot, user_browser, user_browser_version, user_device_type, user_device_vendor, user_device_model, user_os, user_os_version, user_referer
);

END;$function$;
CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$declare
    claims jsonb;
    user_role public.app_role;
    user_plan public.app_plan;
    user_timezone text;
  begin
    -- Fetch the user role in the user_roles table
    -- select role into user_role from public.user_roles where user_id = (event->>'user_id')::uuid;

    -- select plan, timezone into user_plan, user_timezone from public.users_profiles where user_id = (event->>'user_id')::uuid;

    claims := event->'claims';

    -- -- Check if 'app_metadata' exists in claims
    -- if jsonb_typeof(claims->'app_metadata') is null then
    --   -- If 'app_metadata' does not exist, create an empty object
    --   claims := jsonb_set(claims, '{app_metadata}', '{}');
    -- end if;

    -- Check if 'app_metadata' exists in claims
    if jsonb_typeof(claims->'user_metadata') is null then
      -- If 'user_metadata' does not exist, create an empty object
      claims := jsonb_set(claims, '{user_metadata}', '{}');
    end if;

    if user_role is not null then
      -- Set the claim
      claims := jsonb_set(claims, '{user_metadata, user_role}', to_jsonb(user_role));
    else
      claims := jsonb_set(claims, '{user_metadata, user_role}', 'null');
    end if;

    if user_plan is not null then
      -- Set the claim
      claims := jsonb_set(claims, '{user_metadata, user_plan}', to_jsonb(user_plan));
    else
      claims := jsonb_set(claims, '{user_metadata, user_plan}', 'null');
    end if;

    if user_timezone is not null then
      -- Set the claim
      claims := jsonb_set(claims, '{user_metadata, user_timezone}', to_jsonb(user_timezone));
    else
      claims := jsonb_set(claims, '{user_metadata, user_timezone}', 'null');
    end if;

    -- Update the 'claims' object in the original event
    event := jsonb_set(event, '{claims}', claims);

    -- Return the modified or original event
    return event;
  end;$function$;
CREATE OR REPLACE FUNCTION public.fn_log_audit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  v_action text;
BEGIN
  -- Determinar el tipo de operación SQL
  IF (TG_OP = 'INSERT') THEN
    v_action := 'create';
  ELSIF (TG_OP = 'UPDATE') THEN
    v_action := 'update';
  ELSIF (TG_OP = 'DELETE') THEN
    v_action := 'delete';
  ELSE
    v_action := 'unknown';
  END IF;

  -- Insertar registro en audit_log
  INSERT INTO public.audit_logs (
    user_id,
    entity_type,
    entity_id,
    action,
    old_data,
    new_data
  )
  VALUES (
    -- Intentamos tomar el user_id del registro nuevo o viejo
    COALESCE(NEW.user_id, OLD.user_id),
    -- TG_ARGV[0] = argumento que le pasamos al crear el trigger (por ejemplo 'payment')
    TG_ARGV[0],
    -- ID del registro afectado (si es delete no hay NEW, si es insert no hay OLD)
    COALESCE(NEW.id, OLD.id),
    -- Acción detectada (create/update/delete)
    v_action,
    -- Guardamos los valores antiguos y nuevos para auditoría
    to_jsonb(OLD),
    to_jsonb(NEW)
  );

  -- Retornar NEW (necesario para triggers AFTER)
  RETURN NEW;
END;
$function$;
CREATE OR REPLACE FUNCTION public.fn_verify_shortlink_expired()
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$BEGIN

update public.short_links
  set status = false
where 
  status is true 
  and expires_at < CURRENT_TIMESTAMP;

END;$function$;
CREATE OR REPLACE FUNCTION public.get_dashboard_stats_summary(_slugs text[], _start_date timestamp without time zone, _end_date timestamp without time zone, _date_grouping text DEFAULT 'day'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$DECLARE
  day_stats jsonb := '[]'::jsonb;
  top_countries jsonb := '[]'::jsonb;
  top_browsers jsonb := '[]'::jsonb;
  clicks_summary int8 := 0;
  clicks_all_time int8 := 0;
  clicks_last_24h int8 := 0;
BEGIN

  IF _date_grouping NOT IN ('day', 'week', 'month') THEN
    RAISE EXCEPTION 'Invalid date_grouping: %', _date_grouping
      USING ERRCODE = '22023';
  END IF;

  -- Agrega day stats
  SELECT coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb) INTO day_stats
  FROM (
    SELECT
      date_trunc(_date_grouping, date)::date AS date,
      SUM(total_clicks) as clicks
    FROM public.short_links_daily_stats
    WHERE slug = ANY(_slugs) AND date >= _start_date::date AND date <= _end_date::date
    GROUP BY 1
    ORDER BY 1 ASC
  ) t;

  select count(*) into clicks_last_24h
  from public.history_clicks as h
  where 
  h.slug = ANY(_slugs)
  and h.created_at >= (CURRENT_TIMESTAMP - INTERVAL '1 day')
  and h.created_at <= CURRENT_TIMESTAMP;

  select count(*) into clicks_summary
  from public.history_clicks as h
  where 
  h.slug = ANY(_slugs)
  and h.created_at >= _start_date
  and h.created_at <= _end_date;

  SELECT 
    SUM(total_clicks::int) into clicks_all_time
  FROM public.short_links_stats t
  where slug = ANY(_slugs)
  LIMIT 1;

  SELECT coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb) INTO top_countries
  FROM (
    SELECT 
      pairs.key as name,
      SUM(pairs.value::int) as value
    FROM public.short_links_stats t,
         jsonb_each_text(t.country_counts) pairs
    where slug = ANY(_slugs)
    GROUP BY pairs.key
    ORDER BY SUM(pairs.value::int) DESC
    LIMIT 3
  ) t;
  
  SELECT coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb) INTO top_browsers
  FROM (
    SELECT 
      pairs.key as name,
      SUM(pairs.value::int) as value
    FROM public.short_links_stats t,
         jsonb_each_text(t.browser_counts) pairs
    where slug = ANY(_slugs)
    GROUP BY pairs.key
    ORDER BY SUM(pairs.value::int) DESC
    LIMIT 3
  ) t;

  return jsonb_build_object(
    'summary', jsonb_build_object(
      'clicks', clicks_summary,
      'clicks_last_24h', clicks_last_24h,
      'stats', day_stats,
      'date_start', _start_date,
      'date_end', _end_date,
      'date_grouping', _date_grouping
    ),
    'all_time', jsonb_build_object(
      'clicks', clicks_all_time,
      'top_countries', top_countries,
      'top_browsers', top_browsers
    )
  );
END;$function$;
CREATE OR REPLACE FUNCTION public.get_page_clicks_between_dates(_slug text[], _start_date timestamp with time zone, _end_date timestamp with time zone)
 RETURNS bigint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$declare
  total_clicks int8;
begin
select
  count(*) into total_clicks
from public.history_clicks as h
where 
h.slug = ANY(_slug)
and h.created_at >= _start_date
and h.created_at <= _end_date;

return total_clicks;
end;$function$;
CREATE OR REPLACE FUNCTION public.get_page_traffic(_slug text[])
 RETURNS TABLE(referer text, count bigint)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$begin
  return query
select 
  COALESCE(h.referer, '') as referer,
  count(*) as count
from public.history_clicks as h
where 
h.slug = ANY(_slug)
and (
  h.referer is null 
  or (
    h.referer not like 'https://www.iny.one%' 
    and h.referer not like 'https://iny.one%'
  )
)
group by h.referer;
end;$function$;
CREATE OR REPLACE FUNCTION public.update_short_links_daily_monthly_stats()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$declare
  click_date date := new.created_at::date;
  click_year int := extract(year from new.created_at);
  click_month int := extract(month from new.created_at);

  -- Normalización: NULL o '' → 'unknown'
  v_country text := coalesce(nullif(new.country_code, ''), 'unknown');
  v_browser text := coalesce(nullif(new.browser, ''), 'unknown');
  v_os text := coalesce(nullif(new.os, ''), 'unknown');
  v_device_type text := coalesce(nullif(new.device_type, ''), 'unknown');
begin
  -- Ignorar bots
  IF new.is_bot THEN
    RETURN new;
  END IF;

  -------------------------------------
  -- DAILY STATS
  -------------------------------------
  insert into public.short_links_daily_stats (slug, date)
  values (new.slug, click_date)
  on conflict (slug, date) do nothing;

  update public.short_links_daily_stats
  set 
    total_clicks = total_clicks + 1,
    unique_ips = (
      select count(distinct ip)
      from public.history_clicks
      where slug = new.slug
        and is_bot = false
        and created_at::date = click_date
    ),
    country_counts = jsonb_set(
      country_counts,
      array[v_country],
      to_jsonb( coalesce((country_counts ->> v_country)::int, 0) + 1 ),
      true
    ),
    browser_counts = jsonb_set(
      browser_counts,
      array[v_browser],
      to_jsonb( coalesce((browser_counts ->> v_browser)::int, 0) + 1 ),
      true
    ),
    os_counts = jsonb_set(
      os_counts,
      array[v_os],
      to_jsonb( coalesce((os_counts ->> v_os)::int, 0) + 1 ),
      true
    ),
    device_type_counts = jsonb_set(
      device_type_counts,
      array[v_device_type],
      to_jsonb( coalesce((device_type_counts ->> v_device_type)::int, 0) + 1 ),
      true
    ),
    updated_at = now()
  where slug = new.slug and date = click_date;



  -------------------------------------
  -- MONTHLY STATS
  -------------------------------------
  insert into public.short_links_monthly_stats (slug, year, month)
  values (new.slug, click_year, click_month)
  on conflict (slug, year, month) do nothing;

  update public.short_links_monthly_stats
  set 
    total_clicks = total_clicks + 1,
    unique_ips = (
      select count(distinct ip)
      from public.history_clicks
      where slug = new.slug
        and is_bot = false
        and extract(year from created_at) = click_year
        and extract(month from created_at) = click_month
    ),
    country_counts = jsonb_set(
      country_counts,
      array[v_country],
      to_jsonb( coalesce((country_counts ->> v_country)::int, 0) + 1 ),
      true
    ),
    browser_counts = jsonb_set(
      browser_counts,
      array[v_browser],
      to_jsonb( coalesce((browser_counts ->> v_browser)::int, 0) + 1 ),
      true
    ),
    os_counts = jsonb_set(
      os_counts,
      array[v_os],
      to_jsonb( coalesce((os_counts ->> v_os)::int, 0) + 1 ),
      true
    ),
    device_type_counts = jsonb_set(
      device_type_counts,
      array[v_device_type],
      to_jsonb( coalesce((device_type_counts ->> v_device_type)::int, 0) + 1 ),
      true
    ),
    updated_at = now()
  where slug = new.slug
    and year = click_year
    and month = click_month;

  return new;
end;$function$;
CREATE OR REPLACE FUNCTION public.update_short_links_stats()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$declare
  -- Normalización: NULL o '' → 'unknown'
  v_country text := coalesce(nullif(new.country_code, ''), 'unknown');
  v_browser text := coalesce(nullif(new.browser, ''), 'unknown');
  v_os text := coalesce(nullif(new.os, ''), 'unknown');
  v_device_type text := coalesce(nullif(new.device_type, ''), 'unknown');
begin
  IF new.is_bot THEN
    RETURN new;
  END IF;

  -- Asegurar fila existente en stats
  insert into public.short_links_stats (slug)
  values (new.slug)
  on conflict (slug) do nothing;

  -- Incrementar clicks
  update public.short_links_stats
  set
    total_clicks = total_clicks + 1,
    last_click_at = new.created_at,
    -- agrega 1 al país
    country_counts = jsonb_set(
      country_counts,
      array[v_country],
      to_jsonb(
        coalesce((country_counts -> v_country)::text::int, 0) + 1
      ),
      true
    ),
    -- browser
    browser_counts = jsonb_set(
      browser_counts,
      array[v_browser],
      to_jsonb(
        coalesce((browser_counts -> v_browser)::text::int, 0) + 1
      ),
      true
    ),
    -- os
    os_counts = jsonb_set(
      os_counts,
      array[v_os],
      to_jsonb(
        coalesce((os_counts -> v_os)::text::int, 0) + 1
      ),
      true
    ),
    -- device_type
    device_type_counts = jsonb_set(
      device_type_counts,
      array[v_device_type],
      to_jsonb(
        coalesce((device_type_counts -> v_device_type)::text::int, 0) + 1
      ),
      true
    ),
    updated_at = now()
  where slug = new.slug;

  return new;
end;$function$;
CREATE OR REPLACE FUNCTION security.insert_blocked_url(domains text[])
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
DECLARE
  inserted_count integer := 0;
BEGIN
  INSERT INTO security.blocked_url(domain)
  SELECT d
  FROM unnest(domains) AS t(d)
  WHERE d IS NOT NULL
    AND btrim(d) <> ''
  ON CONFLICT (domain) DO NOTHING;

  GET DIAGNOSTICS inserted_count = ROW_COUNT;
  RETURN inserted_count;
END;
$function$;
CREATE OR REPLACE FUNCTION security.is_domain_secure(domain_to_check text)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'security'
AS $function$declare
  domain_found text;
  domain_is_custom bool;

BEGIN
  -- Check if the domain is in any blocked lists
  select
    domain into domain_found
  from security.cached_blocked_url
  where 
    domain = domain_to_check
  limit 1;

  if domain_found is not null then
    return false;
  end if;

  select
    domain into domain_found
  from security.whitelist_url
  where
    domain = domain_to_check
  limit 1;

  if domain_found is not null then
    return true;
  end if;

  select 
    domain,
    is_custom 
    into domain_found, 
    domain_is_custom
  from security.blocked_url
  where 
    domain = domain_to_check 
  limit 1;

  if domain_found is not null then
    insert into security.cached_blocked_url 
        (domain, is_custom) 
      values 
        (domain_to_check, domain_is_custom, domain_is_custom);
    return false;
  end if;

  select
    domain into domain_found
  from security.blocklist_url_phishing_active
  where
    domain = domain_to_check
  limit 1;

  if domain_found is not null then
    insert into security.cached_blocked_url 
        (domain, is_custom, is_permanent) 
      values 
        (domain_to_check, FALSE, FALSE);
    return false;
  end if;

  -- If the domain is not found in any list, cache it as allowed
  INSERT INTO security.whitelist_url (domain, is_custom)
  VALUES (domain_to_check, FALSE);

  return true;

END;$function$;
CREATE OR REPLACE FUNCTION security.is_domain_secure_deep_check()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$declare
  domain_found text;
  domain_is_custom bool;

BEGIN

  if NEW.domain is null then
    return NEW;
  end if;

  -- Check if the domain is in any blocked lists
  select
    domain into domain_found
  from security.cached_blocked_url
  where 
    domain = NEW.domain
  limit 1;

  if domain_found is not null then
    -- UPDATE public.short_links SET status = false WHERE slug = NEW.slug;
    NEW.status := false;
    return NEW;
  end if;

  select 
    domain,
    is_custom 
    into domain_found, 
    domain_is_custom
  from security.blocked_url
  where 
    domain = NEW.domain
  limit 1;

  if domain_found is not null then
    insert into security.cached_blocked_url 
        (domain, is_custom) 
      values 
        (NEW.domain, domain_is_custom, domain_is_custom);
    -- UPDATE public.short_links SET status = false WHERE slug = NEW.slug;
    NEW.status := false;
    return NEW;
  end if;

  select
    domain into domain_found
  from security.blocklist_url_phishing_active
  where
    domain = NEW.domain
  limit 1;

  if domain_found is not null then
    insert into security.cached_blocked_url 
        (domain, is_custom, is_permanent) 
      values 
        (NEW.domain, FALSE, FALSE);
    -- UPDATE public.short_links SET status = false WHERE slug = NEW.slug;
    NEW.status := false;
    return NEW;
  end if;
  
  return NEW;

END;$function$;
grant delete on table "public"."audit_logs" to "anon";
grant insert on table "public"."audit_logs" to "anon";
grant references on table "public"."audit_logs" to "anon";
grant select on table "public"."audit_logs" to "anon";
grant trigger on table "public"."audit_logs" to "anon";
grant truncate on table "public"."audit_logs" to "anon";
grant update on table "public"."audit_logs" to "anon";
grant delete on table "public"."audit_logs" to "authenticated";
grant insert on table "public"."audit_logs" to "authenticated";
grant references on table "public"."audit_logs" to "authenticated";
grant select on table "public"."audit_logs" to "authenticated";
grant trigger on table "public"."audit_logs" to "authenticated";
grant truncate on table "public"."audit_logs" to "authenticated";
grant update on table "public"."audit_logs" to "authenticated";
grant delete on table "public"."audit_logs" to "service_role";
grant insert on table "public"."audit_logs" to "service_role";
grant references on table "public"."audit_logs" to "service_role";
grant select on table "public"."audit_logs" to "service_role";
grant trigger on table "public"."audit_logs" to "service_role";
grant truncate on table "public"."audit_logs" to "service_role";
grant update on table "public"."audit_logs" to "service_role";
grant delete on table "public"."discounts" to "anon";
grant insert on table "public"."discounts" to "anon";
grant references on table "public"."discounts" to "anon";
grant select on table "public"."discounts" to "anon";
grant trigger on table "public"."discounts" to "anon";
grant truncate on table "public"."discounts" to "anon";
grant update on table "public"."discounts" to "anon";
grant delete on table "public"."discounts" to "authenticated";
grant insert on table "public"."discounts" to "authenticated";
grant references on table "public"."discounts" to "authenticated";
grant select on table "public"."discounts" to "authenticated";
grant trigger on table "public"."discounts" to "authenticated";
grant truncate on table "public"."discounts" to "authenticated";
grant update on table "public"."discounts" to "authenticated";
grant delete on table "public"."discounts" to "service_role";
grant insert on table "public"."discounts" to "service_role";
grant references on table "public"."discounts" to "service_role";
grant select on table "public"."discounts" to "service_role";
grant trigger on table "public"."discounts" to "service_role";
grant truncate on table "public"."discounts" to "service_role";
grant update on table "public"."discounts" to "service_role";
grant select on table "public"."domains_to_check" to "PUBLIC";
grant delete on table "public"."domains_to_check" to "anon";
grant insert on table "public"."domains_to_check" to "anon";
grant references on table "public"."domains_to_check" to "anon";
grant select on table "public"."domains_to_check" to "anon";
grant trigger on table "public"."domains_to_check" to "anon";
grant truncate on table "public"."domains_to_check" to "anon";
grant update on table "public"."domains_to_check" to "anon";
grant delete on table "public"."domains_to_check" to "authenticated";
grant insert on table "public"."domains_to_check" to "authenticated";
grant references on table "public"."domains_to_check" to "authenticated";
grant select on table "public"."domains_to_check" to "authenticated";
grant trigger on table "public"."domains_to_check" to "authenticated";
grant truncate on table "public"."domains_to_check" to "authenticated";
grant update on table "public"."domains_to_check" to "authenticated";
grant delete on table "public"."domains_to_check" to "service_role";
grant insert on table "public"."domains_to_check" to "service_role";
grant references on table "public"."domains_to_check" to "service_role";
grant select on table "public"."domains_to_check" to "service_role";
grant trigger on table "public"."domains_to_check" to "service_role";
grant truncate on table "public"."domains_to_check" to "service_role";
grant update on table "public"."domains_to_check" to "service_role";
grant select on table "public"."history_clicks" to "PUBLIC";
grant delete on table "public"."history_clicks" to "anon";
grant insert on table "public"."history_clicks" to "anon";
grant references on table "public"."history_clicks" to "anon";
grant select on table "public"."history_clicks" to "anon";
grant trigger on table "public"."history_clicks" to "anon";
grant truncate on table "public"."history_clicks" to "anon";
grant update on table "public"."history_clicks" to "anon";
grant delete on table "public"."history_clicks" to "authenticated";
grant insert on table "public"."history_clicks" to "authenticated";
grant references on table "public"."history_clicks" to "authenticated";
grant select on table "public"."history_clicks" to "authenticated";
grant trigger on table "public"."history_clicks" to "authenticated";
grant truncate on table "public"."history_clicks" to "authenticated";
grant update on table "public"."history_clicks" to "authenticated";
grant delete on table "public"."history_clicks" to "service_role";
grant insert on table "public"."history_clicks" to "service_role";
grant references on table "public"."history_clicks" to "service_role";
grant select on table "public"."history_clicks" to "service_role";
grant trigger on table "public"."history_clicks" to "service_role";
grant truncate on table "public"."history_clicks" to "service_role";
grant update on table "public"."history_clicks" to "service_role";
grant delete on table "public"."orders" to "anon";
grant insert on table "public"."orders" to "anon";
grant references on table "public"."orders" to "anon";
grant select on table "public"."orders" to "anon";
grant trigger on table "public"."orders" to "anon";
grant truncate on table "public"."orders" to "anon";
grant update on table "public"."orders" to "anon";
grant delete on table "public"."orders" to "authenticated";
grant insert on table "public"."orders" to "authenticated";
grant references on table "public"."orders" to "authenticated";
grant select on table "public"."orders" to "authenticated";
grant trigger on table "public"."orders" to "authenticated";
grant truncate on table "public"."orders" to "authenticated";
grant update on table "public"."orders" to "authenticated";
grant delete on table "public"."orders" to "service_role";
grant insert on table "public"."orders" to "service_role";
grant references on table "public"."orders" to "service_role";
grant select on table "public"."orders" to "service_role";
grant trigger on table "public"."orders" to "service_role";
grant truncate on table "public"."orders" to "service_role";
grant update on table "public"."orders" to "service_role";
grant delete on table "public"."payments" to "anon";
grant insert on table "public"."payments" to "anon";
grant references on table "public"."payments" to "anon";
grant select on table "public"."payments" to "anon";
grant trigger on table "public"."payments" to "anon";
grant truncate on table "public"."payments" to "anon";
grant update on table "public"."payments" to "anon";
grant delete on table "public"."payments" to "authenticated";
grant insert on table "public"."payments" to "authenticated";
grant references on table "public"."payments" to "authenticated";
grant select on table "public"."payments" to "authenticated";
grant trigger on table "public"."payments" to "authenticated";
grant truncate on table "public"."payments" to "authenticated";
grant update on table "public"."payments" to "authenticated";
grant delete on table "public"."payments" to "service_role";
grant insert on table "public"."payments" to "service_role";
grant references on table "public"."payments" to "service_role";
grant select on table "public"."payments" to "service_role";
grant trigger on table "public"."payments" to "service_role";
grant truncate on table "public"."payments" to "service_role";
grant update on table "public"."payments" to "service_role";
grant delete on table "public"."plan_permission" to "anon";
grant insert on table "public"."plan_permission" to "anon";
grant references on table "public"."plan_permission" to "anon";
grant select on table "public"."plan_permission" to "anon";
grant trigger on table "public"."plan_permission" to "anon";
grant truncate on table "public"."plan_permission" to "anon";
grant update on table "public"."plan_permission" to "anon";
grant delete on table "public"."plan_permission" to "authenticated";
grant insert on table "public"."plan_permission" to "authenticated";
grant references on table "public"."plan_permission" to "authenticated";
grant select on table "public"."plan_permission" to "authenticated";
grant trigger on table "public"."plan_permission" to "authenticated";
grant truncate on table "public"."plan_permission" to "authenticated";
grant update on table "public"."plan_permission" to "authenticated";
grant delete on table "public"."plan_permission" to "service_role";
grant insert on table "public"."plan_permission" to "service_role";
grant references on table "public"."plan_permission" to "service_role";
grant select on table "public"."plan_permission" to "service_role";
grant trigger on table "public"."plan_permission" to "service_role";
grant truncate on table "public"."plan_permission" to "service_role";
grant update on table "public"."plan_permission" to "service_role";
grant delete on table "public"."role_permissions" to "anon";
grant insert on table "public"."role_permissions" to "anon";
grant references on table "public"."role_permissions" to "anon";
grant select on table "public"."role_permissions" to "anon";
grant trigger on table "public"."role_permissions" to "anon";
grant truncate on table "public"."role_permissions" to "anon";
grant update on table "public"."role_permissions" to "anon";
grant delete on table "public"."role_permissions" to "authenticated";
grant insert on table "public"."role_permissions" to "authenticated";
grant references on table "public"."role_permissions" to "authenticated";
grant select on table "public"."role_permissions" to "authenticated";
grant trigger on table "public"."role_permissions" to "authenticated";
grant truncate on table "public"."role_permissions" to "authenticated";
grant update on table "public"."role_permissions" to "authenticated";
grant delete on table "public"."role_permissions" to "service_role";
grant insert on table "public"."role_permissions" to "service_role";
grant references on table "public"."role_permissions" to "service_role";
grant select on table "public"."role_permissions" to "service_role";
grant trigger on table "public"."role_permissions" to "service_role";
grant truncate on table "public"."role_permissions" to "service_role";
grant update on table "public"."role_permissions" to "service_role";
grant delete on table "public"."services" to "anon";
grant insert on table "public"."services" to "anon";
grant references on table "public"."services" to "anon";
grant select on table "public"."services" to "anon";
grant trigger on table "public"."services" to "anon";
grant truncate on table "public"."services" to "anon";
grant update on table "public"."services" to "anon";
grant delete on table "public"."services" to "authenticated";
grant insert on table "public"."services" to "authenticated";
grant references on table "public"."services" to "authenticated";
grant select on table "public"."services" to "authenticated";
grant trigger on table "public"."services" to "authenticated";
grant truncate on table "public"."services" to "authenticated";
grant update on table "public"."services" to "authenticated";
grant delete on table "public"."services" to "service_role";
grant insert on table "public"."services" to "service_role";
grant references on table "public"."services" to "service_role";
grant select on table "public"."services" to "service_role";
grant trigger on table "public"."services" to "service_role";
grant truncate on table "public"."services" to "service_role";
grant update on table "public"."services" to "service_role";
grant select on table "public"."short_links" to "PUBLIC";
grant delete on table "public"."short_links" to "anon";
grant insert on table "public"."short_links" to "anon";
grant references on table "public"."short_links" to "anon";
grant select on table "public"."short_links" to "anon";
grant trigger on table "public"."short_links" to "anon";
grant truncate on table "public"."short_links" to "anon";
grant update on table "public"."short_links" to "anon";
grant delete on table "public"."short_links" to "authenticated";
grant insert on table "public"."short_links" to "authenticated";
grant references on table "public"."short_links" to "authenticated";
grant select on table "public"."short_links" to "authenticated";
grant trigger on table "public"."short_links" to "authenticated";
grant truncate on table "public"."short_links" to "authenticated";
grant update on table "public"."short_links" to "authenticated";
grant delete on table "public"."short_links" to "service_role";
grant insert on table "public"."short_links" to "service_role";
grant references on table "public"."short_links" to "service_role";
grant select on table "public"."short_links" to "service_role";
grant trigger on table "public"."short_links" to "service_role";
grant truncate on table "public"."short_links" to "service_role";
grant update on table "public"."short_links" to "service_role";
grant delete on table "public"."short_links_daily_stats" to "anon";
grant insert on table "public"."short_links_daily_stats" to "anon";
grant references on table "public"."short_links_daily_stats" to "anon";
grant select on table "public"."short_links_daily_stats" to "anon";
grant trigger on table "public"."short_links_daily_stats" to "anon";
grant truncate on table "public"."short_links_daily_stats" to "anon";
grant update on table "public"."short_links_daily_stats" to "anon";
grant delete on table "public"."short_links_daily_stats" to "authenticated";
grant insert on table "public"."short_links_daily_stats" to "authenticated";
grant references on table "public"."short_links_daily_stats" to "authenticated";
grant select on table "public"."short_links_daily_stats" to "authenticated";
grant trigger on table "public"."short_links_daily_stats" to "authenticated";
grant truncate on table "public"."short_links_daily_stats" to "authenticated";
grant update on table "public"."short_links_daily_stats" to "authenticated";
grant delete on table "public"."short_links_daily_stats" to "service_role";
grant insert on table "public"."short_links_daily_stats" to "service_role";
grant references on table "public"."short_links_daily_stats" to "service_role";
grant select on table "public"."short_links_daily_stats" to "service_role";
grant trigger on table "public"."short_links_daily_stats" to "service_role";
grant truncate on table "public"."short_links_daily_stats" to "service_role";
grant update on table "public"."short_links_daily_stats" to "service_role";
grant delete on table "public"."short_links_monthly_stats" to "anon";
grant insert on table "public"."short_links_monthly_stats" to "anon";
grant references on table "public"."short_links_monthly_stats" to "anon";
grant select on table "public"."short_links_monthly_stats" to "anon";
grant trigger on table "public"."short_links_monthly_stats" to "anon";
grant truncate on table "public"."short_links_monthly_stats" to "anon";
grant update on table "public"."short_links_monthly_stats" to "anon";
grant delete on table "public"."short_links_monthly_stats" to "authenticated";
grant insert on table "public"."short_links_monthly_stats" to "authenticated";
grant references on table "public"."short_links_monthly_stats" to "authenticated";
grant select on table "public"."short_links_monthly_stats" to "authenticated";
grant trigger on table "public"."short_links_monthly_stats" to "authenticated";
grant truncate on table "public"."short_links_monthly_stats" to "authenticated";
grant update on table "public"."short_links_monthly_stats" to "authenticated";
grant delete on table "public"."short_links_monthly_stats" to "service_role";
grant insert on table "public"."short_links_monthly_stats" to "service_role";
grant references on table "public"."short_links_monthly_stats" to "service_role";
grant select on table "public"."short_links_monthly_stats" to "service_role";
grant trigger on table "public"."short_links_monthly_stats" to "service_role";
grant truncate on table "public"."short_links_monthly_stats" to "service_role";
grant update on table "public"."short_links_monthly_stats" to "service_role";
grant delete on table "public"."short_links_stats" to "anon";
grant insert on table "public"."short_links_stats" to "anon";
grant references on table "public"."short_links_stats" to "anon";
grant select on table "public"."short_links_stats" to "anon";
grant trigger on table "public"."short_links_stats" to "anon";
grant truncate on table "public"."short_links_stats" to "anon";
grant update on table "public"."short_links_stats" to "anon";
grant delete on table "public"."short_links_stats" to "authenticated";
grant insert on table "public"."short_links_stats" to "authenticated";
grant references on table "public"."short_links_stats" to "authenticated";
grant select on table "public"."short_links_stats" to "authenticated";
grant trigger on table "public"."short_links_stats" to "authenticated";
grant truncate on table "public"."short_links_stats" to "authenticated";
grant update on table "public"."short_links_stats" to "authenticated";
grant delete on table "public"."short_links_stats" to "service_role";
grant insert on table "public"."short_links_stats" to "service_role";
grant references on table "public"."short_links_stats" to "service_role";
grant select on table "public"."short_links_stats" to "service_role";
grant trigger on table "public"."short_links_stats" to "service_role";
grant truncate on table "public"."short_links_stats" to "service_role";
grant update on table "public"."short_links_stats" to "service_role";
grant delete on table "public"."subscriptions" to "anon";
grant insert on table "public"."subscriptions" to "anon";
grant references on table "public"."subscriptions" to "anon";
grant select on table "public"."subscriptions" to "anon";
grant trigger on table "public"."subscriptions" to "anon";
grant truncate on table "public"."subscriptions" to "anon";
grant update on table "public"."subscriptions" to "anon";
grant delete on table "public"."subscriptions" to "authenticated";
grant insert on table "public"."subscriptions" to "authenticated";
grant references on table "public"."subscriptions" to "authenticated";
grant select on table "public"."subscriptions" to "authenticated";
grant trigger on table "public"."subscriptions" to "authenticated";
grant truncate on table "public"."subscriptions" to "authenticated";
grant update on table "public"."subscriptions" to "authenticated";
grant delete on table "public"."subscriptions" to "service_role";
grant insert on table "public"."subscriptions" to "service_role";
grant references on table "public"."subscriptions" to "service_role";
grant select on table "public"."subscriptions" to "service_role";
grant trigger on table "public"."subscriptions" to "service_role";
grant truncate on table "public"."subscriptions" to "service_role";
grant update on table "public"."subscriptions" to "service_role";
grant delete on table "public"."user_roles" to "service_role";
grant insert on table "public"."user_roles" to "service_role";
grant references on table "public"."user_roles" to "service_role";
grant select on table "public"."user_roles" to "service_role";
grant trigger on table "public"."user_roles" to "service_role";
grant truncate on table "public"."user_roles" to "service_role";
grant update on table "public"."user_roles" to "service_role";
grant delete on table "public"."user_roles" to "supabase_auth_admin";
grant insert on table "public"."user_roles" to "supabase_auth_admin";
grant references on table "public"."user_roles" to "supabase_auth_admin";
grant select on table "public"."user_roles" to "supabase_auth_admin";
grant trigger on table "public"."user_roles" to "supabase_auth_admin";
grant truncate on table "public"."user_roles" to "supabase_auth_admin";
grant update on table "public"."user_roles" to "supabase_auth_admin";
grant delete on table "public"."users_profiles" to "anon";
grant insert on table "public"."users_profiles" to "anon";
grant references on table "public"."users_profiles" to "anon";
grant select on table "public"."users_profiles" to "anon";
grant trigger on table "public"."users_profiles" to "anon";
grant truncate on table "public"."users_profiles" to "anon";
grant update on table "public"."users_profiles" to "anon";
grant delete on table "public"."users_profiles" to "authenticated";
grant insert on table "public"."users_profiles" to "authenticated";
grant references on table "public"."users_profiles" to "authenticated";
grant select on table "public"."users_profiles" to "authenticated";
grant trigger on table "public"."users_profiles" to "authenticated";
grant truncate on table "public"."users_profiles" to "authenticated";
grant update on table "public"."users_profiles" to "authenticated";
grant delete on table "public"."users_profiles" to "service_role";
grant insert on table "public"."users_profiles" to "service_role";
grant references on table "public"."users_profiles" to "service_role";
grant select on table "public"."users_profiles" to "service_role";
grant trigger on table "public"."users_profiles" to "service_role";
grant truncate on table "public"."users_profiles" to "service_role";
grant update on table "public"."users_profiles" to "service_role";
grant delete on table "public"."webhook_events" to "anon";
grant insert on table "public"."webhook_events" to "anon";
grant references on table "public"."webhook_events" to "anon";
grant select on table "public"."webhook_events" to "anon";
grant trigger on table "public"."webhook_events" to "anon";
grant truncate on table "public"."webhook_events" to "anon";
grant update on table "public"."webhook_events" to "anon";
grant delete on table "public"."webhook_events" to "authenticated";
grant insert on table "public"."webhook_events" to "authenticated";
grant references on table "public"."webhook_events" to "authenticated";
grant select on table "public"."webhook_events" to "authenticated";
grant trigger on table "public"."webhook_events" to "authenticated";
grant truncate on table "public"."webhook_events" to "authenticated";
grant update on table "public"."webhook_events" to "authenticated";
grant delete on table "public"."webhook_events" to "service_role";
grant insert on table "public"."webhook_events" to "service_role";
grant references on table "public"."webhook_events" to "service_role";
grant select on table "public"."webhook_events" to "service_role";
grant trigger on table "public"."webhook_events" to "service_role";
grant truncate on table "public"."webhook_events" to "service_role";
grant update on table "public"."webhook_events" to "service_role";
grant select on table "security"."blocked_url" to "PUBLIC";
grant insert on table "security"."blocked_url" to "service_role";
grant select on table "security"."blocked_url" to "service_role";
grant update on table "security"."blocked_url" to "service_role";
grant select on table "security"."blocklist_url_phishing_active" to "PUBLIC";
grant insert on table "security"."blocklist_url_phishing_active" to "service_role";
grant select on table "security"."blocklist_url_phishing_active" to "service_role";
grant update on table "security"."blocklist_url_phishing_active" to "service_role";
grant select on table "security"."cached_blocked_url" to "PUBLIC";
grant insert on table "security"."cached_blocked_url" to "service_role";
grant select on table "security"."cached_blocked_url" to "service_role";
grant update on table "security"."cached_blocked_url" to "service_role";
grant insert on table "security"."whitelist_url" to "PUBLIC";
grant select on table "security"."whitelist_url" to "PUBLIC";
grant insert on table "security"."whitelist_url" to "service_role";
grant select on table "security"."whitelist_url" to "service_role";
grant update on table "security"."whitelist_url" to "service_role";
create policy "Enable read access for all users"
  on "public"."history_clicks"
  as permissive
  for select
  to public
using (true);
create policy "Allow read for all"
  on "public"."short_links"
  as permissive
  for select
  to public
using (true);
create policy "Allow auth admin to read user roles"
  on "public"."user_roles"
  as permissive
  for select
  to supabase_auth_admin
using (true);
create policy "Allow auth admin to read user roles"
  on "public"."users_profiles"
  as permissive
  for select
  to supabase_auth_admin
using (true);
create policy "Enable read access for all users"
  on "security"."blocked_url"
  as permissive
  for select
  to public
using (true);
create policy "Enable read access for all users"
  on "security"."blocklist_url_phishing_active"
  as permissive
  for select
  to public
using (true);
create policy "Enable read access for all users"
  on "security"."cached_blocked_url"
  as permissive
  for select
  to public
using (true);
create policy "Enable read access for all users"
  on "security"."whitelist_url"
  as permissive
  for select
  to public
using (true);
CREATE TRIGGER tr_history_clicks_after_insert AFTER INSERT ON public.history_clicks FOR EACH ROW EXECUTE FUNCTION public.update_short_links_stats();
CREATE TRIGGER tr_history_clicks_daily_monthly AFTER INSERT ON public.history_clicks FOR EACH ROW EXECUTE FUNCTION public.update_short_links_daily_monthly_stats();
CREATE TRIGGER trg_audit_subscriptions AFTER INSERT OR DELETE OR UPDATE ON public.subscriptions FOR EACH ROW EXECUTE FUNCTION public.fn_log_audit();
-- CREATE TRIGGER enforce_bucket_name_length_trigger BEFORE INSERT OR UPDATE OF name ON storage.buckets FOR EACH ROW EXECUTE FUNCTION storage.enforce_bucket_name_length();
-- CREATE TRIGGER protect_buckets_delete BEFORE DELETE ON storage.buckets FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete();
-- CREATE TRIGGER protect_objects_delete BEFORE DELETE ON storage.objects FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete();
-- CREATE TRIGGER update_objects_updated_at BEFORE UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column();
